### ISSUE TITLE
Integration with other pose estimations 

### ISSUE THREAD

**Issue by Mh-Magdy** [uos/rmcl#3]
On integrating other pose estimations like robot_localization (gps, imu, encoder) or Madgwick Orientation Filter could i provide a pose estimation from these pkgs on the pose and pose_wc topics continuously?

**Comment by amock** [comment]
I have a few busy weeks ahead. That's why I can only give you a very brief answer for now:
- /pose and /pose_wc is meant *only* for occasionally given initial poses
- you can provide any prior odometry you want as tf-transformation

It's very similar to how amcl is doing it. The image at the bottom of their docs is pretty good describing the "tf situation": https://wiki.ros.org/amcl

For using an IMU only, I would try the Madgwick filter and use the orientation as odom frame. It worked well for the Hilti experiments. However, I strongly recommend to fuse everything you have with a kalman filter to additionally get a prior translational estimate.

Another hint: Look at the examples linked in this repository. If I remember right, there should be a Kalman filter fusing IMU and wheel odometry and the result is used as odometry prior for MICP-L.

Best
Alex

**Comment by amock** [comment]
Hi @Mh-Magdy,

this is a follow-up to my previous answer.

### Kalman-Filter

in [rmcl_example](https://github.com/amock/rmcl_example), there is indeed a kalman filter of the package `robot_pose_ekf` fusing wheel odometry and IMU measurements to a combined estimation expressed as tf transformation from `base` (or `base_footprint`) to `odom`. On the noetic branch `start_robot.launch`, Line 94:

```xml
 <!-- EKF providing the odom frame -->
    <node pkg="robot_pose_ekf" type="robot_pose_ekf" name="robot_pose_ekf" output="screen">
        <param name="freq" value="100.0"/>
        <param name="sensor_timeout" value="1.0"/>
        <param name="publish_tf" value="true"/>
        <param name="odom_used" value="true"/>
        <param name="imu_used" value="true"/>
        <param name="vo_used" value="false"/>
        <remap from="imu_data" to="imu/data"/>
</node>
```

The kalman filter implemented in `robot_localization` does the same. We used it for the ROS2 examples on the humble branch. File `start_robot_launch.py`, Line 106:

```python
ekf = Node(
            package='robot_localization',
            executable='ekf_node',
            name='ekf_filter_node',
            output='screen',
            parameters=[
                {"use_sim_time" : True}, 
                os.path.join(config_dir, 'ekf.yaml')],
           )
```

I also sometimes use the Madgwick Filter to estimate a smooth orientation before fusing it with the wheel odometry using a kalman filter. Then again, the kalman filter already produces the required tf transform.

### IMU-only

However, if you only have an IMU to estimate an prior odometry you could use the Magwick Filter as follows:

```xml
<node pkg="imu_filter_madgwick" type="imu_filter_node" name="imu_filter_node">
    <remap from="/imu/data" to="/ouster/imu_filtered"/>
    <remap from="/imu/data_raw" to="/ouster/imu" />

    <param name="gain" value="0.1" />
    <param name="zeta" value="0.0" />

    <param name="use_mag" value="false" />
    <param name="remove_gravity_vector" value="false" />

    <param name="fixed_frame" value="madgwick" />
    <param name="publish_tf" value="true" />
    <param name="reverse_tf" value="true" />
</node>
```

This config uses the imu data of an ouster sensor and writes the results to the `/ouster/imu_filtered` topic. In addition, it broadcasts a frame `madgwick` below the imu frame in your tf tree. The IMU orientation of the Madgwick Filter is expressed relative to this frame. Using the Madgwick filter orientation as odometry prior is simply setting the `madgwick` frame equal to the `odom` frame. Thus we can determine the missing `base` to `odom` transform as follows:

$$T_{odom \leftarrow base} = T_{madgwick \leftarrow imu} \cdot T_{imu \leftarrow base}$$

The resulting transform can be broadcasted using TF which gives you the required odom prior as proper tf, estimated only from the Madgwick filter. This node is essentially doing this: https://github.com/amock/micp_experiments/blob/main/micp_experiments_helper/src/leaf_odom_to_root.cpp , only that the names of the frames are a bit more general.

### Pose Topic

A pose topic alone won't work, since only tf transforms are accepted as odom prior. However, given you have a tf tree of your robot, I am sure you can translate the pose to a suitable tf transformation.


Best
Alex

**Comment by Mh-Magdy** [comment]
Hi **Alex** @amock,

Thank you for the effort and time you dedicated to this answer. I followed your guidance and provided an Odom frame as a prior from the robot_localization package. After integrating this setup, the RMSE evaluation showed an improvement. Thank you for your invaluable help!

Testing Images

![image](https://github.com/user-attachments/assets/b39259aa-e467-4bc9-bc7e-e98d403864a0)

and after integration: 

![image](https://github.com/user-attachments/assets/6bf1ec3f-b93b-4150-a9a3-b2ae172e7495)

**Comment by amock** [comment]
This looks great! It’s also nice to see the results improving as expected.

I also plan to integrate the world you used into [mesh_navigation_tutorials](https://github.com/naturerobots/mesh_navigation_tutorials), which provides examples for mesh navigation using ROS 2. I may reach out to you again when we start incorporating localization examples into those tutorials. If you're OK with it, we’d love to use some of your results and recorded images there.

Regarding this Github-Issue, I hope to find time soon to create a guide from it, and collecting various strategies for using external pose estimations there. For now, I think we can consider this issue closed.
